#!/usr/bin/bash
##  Bash script to make  an API request for Pikachu pokemon
# on error,  erro msg is saved to  file
# on sucess, response is saved to file
# json response is handled with jq

curl -X GET 'https://pokeapi.co/api/v2/pokemon/Pikachu' 2> errors.txt | jq . > data.json

if [ $? -ne 0 ]; then        # $? is the bash variable for the exit code of the last command
	echo "curl failed with error: $(cat error.log)"   # $(...) is command substitution syntax;
                                                      # the command inside is executed and the result outputted as a string
	exit 1  # terminates script, gives it a non-zero(failing exit code)
fi


